name: Deploy README

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload README file
        uses: actions/upload-artifact@v2
        with:
          name: README
          path: ./first-branch/README.md

      - name: Download README file
        uses: actions/download-artifact@v2
        with:
          name: README
          path: ./test

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update README"
          git push

